export const esConjugations = [
    {
        i: 'estar',
        "present": ["estoy", "estás", "está", "estamos", "estáis", "están"],
        "imperfect": ["estaba", "estabas", "estaba", "estábamos", "estabais", "estaban"],
        "future": ["estaré", "estarás", "estará", "estaremos", "estaréis", "estarán"],
        "preterite": ["estuve", "estuviste", "estuvo", "estuvimos", "estuvisteis", "estuvieron"],
        "past perfect": ["he estado", "has estado", "ha estado", "hemos estado", "habéis estado", "han estado"],
        "pluperfect": ["había estado", "habías estado", "había estado", "habíamos estado", "habíais estado", "habían estado"],
        "future perfect": ["habré estado", "habrás estado", "habrá estado", "habremos estado", "habréis estado", "habrán estado"],
        "past anterior": ["hube estado", "hubiste estado", "hubo estado", "hubimos estado", "hubisteis estado", "hubieron estado"],
        conditional: ['estaría','estarías','estaría','estaríamos','estaríais','estarían'],
        "present subjunctive":["esté","estés","esté","estemos","estéis","estén"],
        "imperfect subjunctive":["estuviera","estuvieras","estuviera","estuviéramos","estuvierais","estuvieran"],
        "pluperfect subjunctive":["hubiera estado","hubieras estado","hubiera estado","hubiéramos estado","hubierais estado","hubieran estado"],
        "present perfect subjunctive":["haya estado","hayas estado","haya estado","hayamos estado","hayáis estado","hayan estado"],
    },
    {
        i: 'ser',
        "present": ["soy", "eres", "es", "somos", "sois", "son"],
        "imperfect": ["era", "eras", "era", "éramos", "erais", "eran"],
        "future": ["seré", "serás", "será", "seremos", "seréis", "serán"],
        "preterite": ["fui", "fuiste", "fue", "fuimos", "fuisteis", "fueron"],
        "past perfect": ["he sido", "has sido", "ha sido", "hemos sido", "habéis sido", "han sido"],
        "pluperfect": ["había sido", "habías sido", "había sido", "habíamos sido", "habíais sido", "habían sido"],
        "future perfect": ["habré sido", "habrás sido", "habrá sido", "habremos sido", "habréis sido", "habrán sido"],
        "past anterior": ["hube sido", "hubiste sido", "hubo sido", "hubimos sido", "hubisteis sido", "hubieron sido"],
        conditional: ['sería','serías','sería','seríamos','seríais','serían'],
        "present subjunctive": ["sea", "seas", "sea", "seamos", "seáis", "sean"],
        "imperfect subjunctive": ["fuera / fuese", "fueras / fueses", "fuera / fuese", "fuéramos / fuésemos", "fuerais / fueseis", "fueran / fuesen"],
        "present perfect subjunctive": ["haya sido", "hayas sido", "haya sido", "hayamos sido", "hayáis sido", "hayan sido"],
        "pluperfect subjunctive": ["hubiera/hubiese sido", "hubieras/hubieses sido", "hubiera/hubiese sido", "hubiéramos/hubiésemos sido", "hubierais/hubieseis sido", "hubieran/hubiesen sido"],
    },
    {
        i: 'dar',        
        "present": ["doy", "das", "da", "damos", "dais", "dan"],
        "imperfect": ["daba", "dabas", "daba", "dábamos", "dabais", "daban"],
        "future": ["daré", "darás", "dará", "daremos", "daréis", "darán"],
        "preterite": ["di", "diste", "dio / dió", "dimos", "disteis", "dieron"],
        "past perfect": ["he dado", "has dado", "ha dado", "hemos dado", "habéis dado", "han dado"],
        "pluperfect": ["había dado", "habías dado", "había dado", "habíamos dado", "habíais dado", "habían dado"],
        "future perfect": ["habré dado", "habrás dado", "habrá dado", "habremos dado", "habréis dado", "habrán dado"],
        "past anterior": ["hube dado", "hubiste dado", "hubo dado", "hubimos dado", "hubisteis dado", "hubieron dado"],
        conditional: ['daría','darías','daría','daríamos','daríais','darían'],
        "present subjunctive": ["dé", "des", "dé", "demos", "deis", "den"],
        "imperfect subjunctive": ["diera / diese", "dieras / dieses", "diera / diese", "diéramos / diésemos", "dierais / dieseis", "dieran / diesen"],
        "present perfect subjunctive": ["haya dado", "hayas dado", "haya dado", "hayamos dado", "hayáis dado", "hayan dado"],
        "pluperfect subjunctive": ["hubiera/hubiese dado", "hubieras/hubieses dado", "hubiera/hubiese dado", "hubiéramos/hubiésemos dado", "hubierais/hubieseis dado", "hubieran/hubiesen dado"]
    },
    {
        i: 'hacer',
        "present": ["hago", "haces", "hace", "hacemos", "hacéis", "hacen"],
        "imperfect": ["hacía", "hacías", "hacía", "hacíamos", "hacíais", "hacían"],
        "future": ["haré", "harás", "hará", "haremos", "haréis", "harán"],
        "preterite": ["hice", "hiciste", "hizo", "hicimos", "hicisteis", "hicieron"],
        "past perfect": ["he hecho", "has hecho", "ha hecho", "hemos hecho", "habéis hecho", "han hecho"],
        "pluperfect": ["había hecho", "habías hecho", "había hecho", "habíamos hecho", "habíais hecho", "habían hecho"],
        "future perfect": ["habré hecho", "habrás hecho", "habrá hecho", "habremos hecho", "habréis hecho", "habrán hecho"],
        "past anterior": ["hube hecho", "hubiste hecho", "hubo hecho", "hubimos hecho", "hubisteis hecho", "hubieron hecho"],
        conditional: ['haría','harías','haría','haríamos','haríasi','harían'],
        "present subjunctive": ["haga", "hagas", "haga", "hagamos", "hagáis", "hagan"],
        "imperfect subjunctive": ["hiciera", "hicieras", "hiciera", "hiciéramos", "hicierais", "hicieran"],
        "past perfect subjunctive": ["haya hecho", "hayas hecho", "haya hecho", "hayamos hecho", "hayáis hecho", "hayan hecho"],
        "pluperfect subjunctive": ["hubiera/hubiese hecho", "hubieras/hubieses hecho", "hubiera/hubiese hecho", "hubiéramos/hubiésemos hecho", "hubierais/hubieseis hecho", "hubieran/hubiesen hecho"]
    }
];